name = "cloudsubmarine"
main = "build/worker/shim.mjs"
compatibility_date = "2023-10-30"

[build]
command = "cargo install -q worker-build && worker-build --release"

[vars]
ROUTES = '{"/api/": "https://api.example.com/", "/blog/": "https://blog.example.com/"}'
